### ISSUE TITLE
v1.0.0までのマイルストーン

### ISSUE THREAD

**Issue by tani** [ta2gch/yomu#1]
- [x] 不要なボタンの削除
- [x] "このソフトウェアについて"ボタンを追加
- [x] macOSのサポート
- [x] Travis CIを回す
- [x] secondaryToolBarの編集
- [x] 曖昧検索の精度向上
- [x] Windowsのインストーラーの動作確認
- [x] サンプルのPDFが大きすぎるので変える

**Comment by ta2gch** [comment]
Travis CIからReleaseを出したいが、

[Error: GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"](https://travis-ci.org/ta2gch/yomu#L1448)

となってできない。
